name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature. Please describe your idea below.
        **Learn more:** [README](https://github.com/bchainhub/well-known/blob/main/README.md)

  - type: textarea
    id: problem
    attributes:
      label: Problem or use case
      description: Is your feature related to a problem? Describe the use case.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the feature or change you'd like
      placeholder: "A new endpoint / parameter / behavior that..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds you've considered
      placeholder: "Optional"
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: API design notes, compatibility, or examples
      placeholder: "Optional: example request/response, link to spec..."
    validations:
      required: false
