name: Token Request
description: Request to add a new token to the well-known registry
title: "[TOKEN REQUEST] "
labels: ["token-request", "enhancement"]
assignees: ["rastislavcore"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for requesting to add a new token to the well-known registry.
        Please fill out all **required** fields below. Optional fields can be left blank.

  - type: input
    id: token-address
    attributes:
      label: Token Address
      description: The blockchain address of the token
      placeholder: "cb19c7acc4c292d2943ba23c2eaa5d9c5a6652a8710c"
    validations:
      required: true

  - type: input
    id: ticker
    attributes:
      label: Ticker
      description: The trading symbol of the token (e.g., CTN, BTC, ETH)
      placeholder: "CTN"
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: Token Name
      description: The full name of the token
      placeholder: "CoreToken"
    validations:
      required: true

  - type: input
    id: symbol
    attributes:
      label: Display Symbol
      description: The display symbol of the token (e.g., ∆á, ‚Çø, Œû)
      placeholder: "∆á"
    validations:
      required: true

  - type: input
    id: decimals
    attributes:
      label: Decimals
      description: Number of decimal places for the token (0-255)
      placeholder: "18"
    validations:
      required: true

  - type: input
    id: type
    attributes:
      label: Token Type
      description: The token type (e.g., CBC20, CBC721, ERC20, ERC721)
      placeholder: "CBC20"
    validations:
      required: true

  - type: input
    id: blockchain
    attributes:
      label: Blockchain
      description: The blockchain name (e.g., core, ethereum, bitcoin)
      placeholder: "core"
    validations:
      required: true

  - type: input
    id: network
    attributes:
      label: Network
      description: The blockchain network where this token exists (e.g., xcb, btc, eth). Use xab, testnet, etc. for testnets; testnet is auto-detected from the network name.
      placeholder: "xcb"
    validations:
      required: true

  - type: input
    id: chain-id
    attributes:
      label: Chain ID
      description: Chain ID number (optional, leave empty if not applicable)
      placeholder: "1"
    validations:
      required: false

  - type: input
    id: genesis
    attributes:
      label: Genesis Date/Time
      description: When the token was first released/created (ISO 8601 format, optional)
      placeholder: "2023-11-17T17:23:50.000Z"
    validations:
      required: false

  - type: input
    id: expiration
    attributes:
      label: Expiration Date/Time
      description: When the token expires (ISO 8601 format, optional - leave empty if never expires)
      placeholder: "2025-12-31T23:59:59.000Z"
    validations:
      required: false

  - type: input
    id: upcoming
    attributes:
      label: Upcoming Date/Time
      description: When the token will become available (ISO 8601 format, optional - leave empty if available now)
      placeholder: "2024-01-01T00:00:00.000Z"
    validations:
      required: false

  - type: input
    id: url
    attributes:
      label: Project Website URL
      description: Official website or documentation URL (optional)
      placeholder: "https://example.com"
    validations:
      required: false

  - type: input
    id: alt-symbol
    attributes:
      label: Alternative Symbol
      description: Alternative symbol for the token (optional, e.g., C for ∆á)
      placeholder: "C"
    validations:
      required: false

  - type: input
    id: flag
    attributes:
      label: Flag Emoji
      description: Emoji flag representing the token's origin (optional)
      placeholder: "üè¥‚Äç‚ò†Ô∏è"
    validations:
      required: false

  - type: input
    id: total-supply
    attributes:
      label: Total Supply
      description: Total supply of tokens as a string (optional)
      placeholder: "1000000000000000000000000"
    validations:
      required: false

  - type: input
    id: categories
    attributes:
      label: Categories
      description: Comma-separated list of categories (e.g., rwa, stable, defi)
      placeholder: "rwa,stable"
    validations:
      required: false

  - type: checkboxes
    id: alt-counting
    attributes:
      label: Alternative Counting
      description: Check if this token uses alternative counting method
      options:
        - label: Token uses alternative counting method
          required: false

  - type: textarea
    id: logos
    attributes:
      label: Logos JSON
      description: JSON object with logo URLs by format (png, svg) and size (16, 32, 48, 64, 128, 256). See README for the exact structure.
      placeholder: '{"png": {"16": "https://‚Ä¶", "32": "https://‚Ä¶", "48": "https://‚Ä¶"}, "svg": {"16": "https://‚Ä¶", "32": "https://‚Ä¶", "48": "https://‚Ä¶"}}'
    validations:
      required: false

  - type: textarea
    id: project-description
    attributes:
      label: Project Description
      description: Brief description of the token and its purpose (for review purposes, not stored in registry)
      placeholder: "Describe what this token is used for and its main features‚Ä¶"
    validations:
      required: false

  - type: input
    id: founder-name
    attributes:
      label: Founder/Team Name
      description: Name of the founder or development team (for review purposes, not stored in registry)
      placeholder: "John Doe"
    validations:
      required: false

  - type: input
    id: founder-contact
    attributes:
      label: Founder/Team Contact
      description: Contact information (email, social media, etc.) (for review purposes, not stored in registry)
      placeholder: "contact@example.com"
    validations:
      required: false

  - type: checkboxes
    id: verification
    attributes:
      label: Verification Checklist
      description: Please confirm the following
      options:
        - label: I confirm that the token address is valid and belongs to the project
          required: true
        - label: I confirm that the provided information is accurate
          required: true
        - label: I understand that false information may result in token removal
          required: true
        - label: I have permission to request this token addition
          required: true

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Any additional information or context
      placeholder: "Any other relevant information‚Ä¶"
    validations:
      required: false
